### ISSUE TITLE
libmysqlcppconn7v5 depende de libmysqlclient20 e não libmysqlclient18 em Ubuntu 16.04

### ISSUE THREAD

**Issue by tuberculo** [potuz/denet#4]
Obtenho a seguinte mensagem de erro após o comando `sudo dpkg -i denet_0.1-1_amd64.deb`.

`A preparar para desempacotar denet_0.1-1_amd64.deb ...
A descompactar denet (0.1-1) ...
dpkg: problemas com dependências impedem a configuração de denet:
 denet depende de libmysqlclient18; porém:
  Pacote libmysqlclient18 não está instalado.
 denet depende de libqt5charts5; porém:
  Pacote libqt5charts5 não está instalado.
 denet depende de libqt5concurrent5 (>= 5.6.0~rc); porém:
  Versão de libqt5concurrent5:amd64 no sistema é 5.5.1+dfsg-16ubuntu7.2.
 denet depende de libqt5core5a (>= 5.7.0); porém:
  Versão de libqt5core5a:amd64 no sistema é 5.5.1+dfsg-16ubuntu7.2.
 denet depende de qt5-default (>= 5.7); porém:
  Versão de qt5-default:amd64 no sistema é 5.5.1+dfsg-16ubuntu7.2.

dpkg: erro ao processar o pacote denet (--install):
 problemas de dependência - deixando desconfigurado
A processar 'triggers' para libc-bin (2.23-0ubuntu4) ...
Erros foram encontrados durante o processamento de:
 denet
`
O que mais chama a atenção é que pede libmysqlclient18, sendo que libmysqlclient20 esta instalado.

**Comment by potuz** [comment]
Sim, o problema de libmysqclient em Ubuntu eu já tenho visto, é devido a que cppconnector utiliza esta biblioteca. Eu não tenho Ubuntu para testar mas acho que posso resolver aquele problema para você. O que eu não posso te ajudar é instalando qt5.7 completo, pelas suas mensagens você não tem isto instalado. Assim que você conseguir instalar qt5.7, pode abrir um "issue" em github referente ao libmysqclient que eu resolvo para você.


Abraços

P

**Comment by potuz** [comment]
Esquece o negócio do "issue" só agora notei que o email era de github.

Continuarei lá

P

**Comment by potuz** [comment]
O problema de libmysqlclient18 vs libmysqlclient20 é com o pacote libmysqlcppconn7v5 que em Debian depende de libmysqlclient18 e em Ubuntu depdende de libmysqlclient20. Devo recompilar o pacote para criar um .deb que funcione em Ubuntu, mas não tenho neste momento acesso a um sistema com Ubuntu. Tentarei instalar um nestes próximos dias. 

O resto do problema é a falta de Qt5.7,

**Comment by potuz** [comment]
Atualizei o [release](https://github.com/potuz/denet/releases) com um pacote para Ubuntu e instruções para instalação do Qt5.7. Fecharei o issue, poste novamente se tiver o mesmo problema. Obrigado por reportá-lo
