### ISSUE TITLE
Dados Carregando como 0.

### ISSUE THREAD

**Issue by Lvitor** [potuz/denet#6]
Alguns balanços (BBAS3 1T12) quando filtramos no banco de dados por 
	
name = Ativo Total
balance_type = 2
financial_info_type = 2

O resultado "value" é igual a zero. Observei também que caso selecione financial_info_type = 1 o valor é 913866693. Porém em outros trimestre o financial_info_type = 2 é diferente de zero.

**Comment by Lvitor** [comment]
Informo também que o mesmo problema ocorreu nos trimestre 2015-03-31 e 2015-09-30. Abraços!

**Comment by potuz** [comment]
O Banco do Brasil informa só resultados individuais para os ITR e ambos individuais e consolidados para os DFP. 

Closes #6
