### ISSUE TITLE
QuantidadeTotalAcaoCapitalIntegralizado Saldo Negativo para BBAS3

### ISSUE THREAD

**Issue by Lvitor** [potuz/denet#8]
Olá Potuz, 
Compile e rodei a sua nova versão, mas a QuantidadeTotalAcaoCapitalIntegralizado continua com saldo negativo para as acoes do BBAS3.

Abraços.

**Comment by potuz** [comment]
Você compilou o Master em Git?

P

**Comment by Lvitor** [comment]
Sim, compilei o master. Inclusive para enviar manualmente pelo denet um arquivo aparece o seguinte erro:

denet -s teste --importe 02247020150930301.zip
terminate called after throwing an instance of 'std::runtime_error'
  what():   copy_data(): r!= ARCHIVE_OK 
Abortado (imagem do núcleo gravada)

**Comment by potuz** [comment]
São dois erros diferentes, o segundo é um erro de libarchive, pode me enviar por e-mail o .zip que está dando o erro?  Se continuar a dar aquele erro por favor abrir um novo issue. 

Referente  a este issue, eu estou vendo valores positivos para a quantidade de ações no BBAS e não consigo reproduzir seu problema. Pode apagar a tabela no mysql e voltar a importar o balanço para checar?

**Comment by Lvitor** [comment]
Posso enviar para este email? potuz@potuz.net?

Muito Obrigado!

**Comment by Lvitor** [comment]
Apenas para ficar claro o que fiz até agora. Criei um maquina virtual com Ubuntu 16.04.
Carreguei todas essas bibliotecas. 

sudo apt-get install mysql-server
sudo apt-get install mysql-client
sudo apt-get install mysql-workbench

sudo apt-get install mesa-common-dev
sudo apt-get install libmysqlcppconn-dev
sudo apt-get install libmysqlclient-dev
sudo apt-get install cmake
sudo apt-get install cmake-gui
sudo apt-get install libcurl3

no libarchive:
sudo  ./configure
sudo  make
sudo  make install

Coloquei esse caminho no CMakeLists.txt
set(CMAKE_PREFIX_PATH /opt/Qt5.7/5.7/gcc_64)

Copiei os arquivo Qtconcurrent para a pasta /usr/local/lib.

**Comment by Lvitor** [comment]
Potuz, Consegui!! Valeu pela ajuda. Vou fazer um texto para ajudar outros na criar o executavel. Só uma dúvida se voce sabe, nos resultados trimestrais não aparece o numero de acoes ? apenas no de fechamento do ano? Sabe dizer.

Abraços.

**Comment by potuz** [comment]
Lvitor, estou fechando esse issue pois não entendo se é ou não um issue. Pode se comunicar pelo email acima se tiver dúvidas. E sim, pode enviar para aquele email o arquivo.  Com respeito aos números de ações, as empresas normalmente disponibilizam eles em todos os resultados, porém a descomposição em tipos diferentes de PN só no FR.
